name: Semgrep
version: 1.131.0-1.2.1
origin: https://github.com/semgrep/semgrep
info: Find patterns of vulnerabilities in smart contracts
image: smartbugs/semgrep:1.131.0-1.2.1
bin: scripts
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN'"

